version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/tree/develop/Program%20Files
    docker:
      - image: cimg/node:lts
    steps:
      -checkout:
        path: ~?https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/tree/develop/Program%20Files
      -run: npm install